---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: getourneau/alpine-bash-git
inputs:
  - name: repo-rc
    path: repo-target
  - name: repo-develop
    path: repo
outputs:
  - name: out
run:
  path: sh
  args:
    - repo/ci/tasks/merge.sh
