---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: getourneau/alpine-bash-git
inputs:
  - name: repo
  - name: version
run:
  path: sh
  args:
    - repo/ci/tasks/shipit.sh
